# Generated by Django 4.1.3 on 2022-11-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='emp_gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Laki-laki'), (2, 'Perempuan')], null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='emp_marital',
            field=models.IntegerField(blank=True, choices=[(1, 'Kawin'), (2, 'Belum Kawin'), (3, 'Cerai')], null=True),
        ),
    ]
