# Generated by Django 4.1.3 on 2022-11-12 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employes', '0002_alter_employe_emp_gender_alter_employe_emp_marital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
